# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78f25844dbc1870fc17628f33dfbf3428d3bfedb53a35631d0b84e2fcb00a452437b6d85c35dca00feec016e22c6687702455efd1b4505a19ee5677aa4661fc0

test:
  secret_key_base: 9050191efa04c7765324e4c6a8894dfb831b74e9eaa19d0e4261ae98997ae0be8b5d3efd503c4274947c39505bf0c85dcf6d8fc7f756547318149a4ff84e811c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
